CREATE USER IF NOT EXISTS 'xtsebas'@'%' IDENTIFIED BY 'xtsebas';
GRANT ALL PRIVILEGES ON blog_db.* TO 'xtsebas'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS anime (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    sinopsis TEXT NOT NULL,
    gender VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
